from thematic.themes import base


class Onedark(base.Theme):
    name = "onedark"
    foreground = "#B2BED1"
    background = "#282C34"
    bg_bright = "#2C323D"
    bg_brighter = "#393f4a"
    bg_brightest = "#505868"

    black = "#393f4a"
    red = "#ff6c6b"
    green = "#98C379"
    yellow = "#ecbe7b"
    blue = "#51afef"
    purple = "#c678dd"
    cyan = "#46d9ff"
    cyan_bright = "#4db5bd"
    white = "#b9bfc9"
    black_bright = "#6f7683"
    red_bright = "#c9665b"
    green_bright = "#62ac65"
    yellow_bright = "#d9a97c"
    blue_bright = "#71bdf2"
    purple_bright = "#a9a1e1"
    white_bright = "#afb0b5"

    bat_theme = "TwoDark"
    autosuggestions = "238"
    tmux_mode_fg = blue

    xcolors = base.Xcolors(
        foreground=foreground,
        background=background,
        xcolors_00=black,
        xcolors_01=red,
        xcolors_02=green,
        xcolors_03=yellow,
        xcolors_04=blue,
        xcolors_05=purple,
        xcolors_06=cyan,
        xcolors_07=white,
        xcolors_08=black_bright,
        xcolors_09=red_bright,
        xcolors_10=green_bright,
        xcolors_11=yellow_bright,
        xcolors_12=blue_bright,
        xcolors_13=purple_bright,
        xcolors_14=cyan_bright,
        xcolors_15=white_bright
    )
    nvim_core = base.NeovimTheme(
        Boolean={"fg": yellow},
        Comment={"fg": bg_bright},
        Constant={"fg": cyan},
        Character={"fg": green},
        Conditional={"fg": purple},
        Define={"fg": purple},
        Error={"fg": red},
        Exception={"fg": purple},
        Float={"fg": yellow},
        Function={"fg": blue},
        Identifier={"fg": red},
        Include={"fg": blue},
        Keyword={"fg": red},
        Label={"fg": purple},
        Macro={"fg": purple},
        Number={"fg": yellow},
        Operator={"fg": purple},
        PreProc={"fg": yellow},
        PreCondit={"fg": yellow},
        Repeat={"fg": purple},
        Statement={"fg": purple},
        StorageClass={"fg": yellow},
        Special={"fg": blue},
        SpecialChar={"fg": yellow},
        Structure={"fg": yellow},
        String={"fg": green},
        SpecialComment={"fg": bg_bright},
        Typedef={"fg": yellow},
        Type={"fg": yellow},
        Todo={"fg": purple},
        Underlined={"style": 'underline'},
        TSNumber={"fg": yellow },
        TSAttribute={"fg": purple},
        TSFunction={"fg": blue},
        TSProperty={"fg": purple},
        TSConstructor={"fg": purple},
        TSLabel={"fg": purple},
        TSKeywordFunction={"fg": purple},
        TSKeywordOperator={"fg": purple},
        TSOperator={"fg": yellow},
        TSInclude={"fg": red},
        BufferInactive={"fg": foreground, "bg": bg_bright},
        BufferInactiveTarge={"fg": foreground, "bg": bg_bright},
        BufferInactiveSign={"fg": blue, "bg": bg_bright},
        BufferCurrent={"fg": yellow, "bg": background, "style": "bold"},
        BufferCurrentSign={"fg": blue, "bg": background},
        BufferTabPageFill={"fg": blue, "bg": background},
        BufferCurrentMod={"fg": blue, "bg": background},
        BufferInactiveMod={"fg": blue, "bg": bg_bright},
        ColorColumn={"fg": "NONE", "bg": bg_bright },
        Conceal={"fg": bg_bright, "bg": "NONE" },
        CursorLineNr={"fg": blue},
        CursorIM={"fg": "NONE", "bg": "NONE", "style": "reverse"},
        CursorColumn={"fg": "NONE", "bg": black_bright}, 
        CursorLine={"fg": "NONE", "bg": bg_bright},
        Cursor={"fg": "NONE", "bg": "NONE", "style": "reverse"},
        DiffAdd={"fg": background, "bg": green},
        DiffChange={"fg": background, "bg": yellow},
        DiffDelete={"fg": background, "bg": red},
        DiffText={"fg": background, "bg": foreground},
        Directory={"fg": bg_bright, "bg": "NONE"},
        debugBreakpoint={"fg": background, "bg": red},
        EndOfBuffer={"fg": background, "bg": "NONE"},
        ErrorMsg={"fg": red, "bg": "NONE", "style": 'bold'},
        FoldColumn={"fg": foreground, "bg": background},
        Folded={"fg": bg_bright, "bg": bg_bright},
        iCursor={"fg": bg_bright, "bg": "NONE", "style": 'reverse'},
        IncSearch={"fg": bg_bright, "bg": yellow, "style": "NONE"},
        lCursor={"fg": "NONE", "bg": "NONE", "style": 'reverse'},
        LineNr={"fg": bg_brighter},
        ModeMsg={"fg": foreground, "bg": "NONE", "style": 'bold'},
        MatchParen={"fg": red, "bg": "NONE"},
        NormalFloat={"fg": foreground, "bg": bg_bright},
        NonText={"fg": bg_bright},
        Pmenu={"fg": foreground, "bg": bg_bright},
        PmenuSel={"fg": bg_bright, "bg": blue},
        PmenuSelBold={"fg": bg_bright, "g": blue},
        PmenuSbar={"fg": "NONE", "bg": bg_bright},
        PmenuThumb={"fg": purple, "bg": green},
        Question={"fg": yellow},
        QuickFixLine={"fg": purple, "style": 'bold'},
        StatusLine={"fg": bg_bright, "bg": bg_brighter, "style": "NONE"}, 
        StatusLineNC={"fg": bg_bright, "bg": bg_bright, "style": "NONE"},
        SpellBad={"fg": red, "bg": "NONE", "style": 'undercurl'},
        SpellCap={"fg":"bue", "bg": "NONE", "style": 'undercurl'},
        SpellLocal={"fg": cyan, "bg": "NONE","style": 'undercurl'},
        SpellRare={"fg": purple, "bg": "NONE", "style": 'undercurl'},
        Search={"fg": background, "bg": yellow},
        SpecialKey={"fg": bg_bright},
        TabLineSel={"bg": background},
        Title={"fg": green, "style": 'bold'},
        Terminal={"fg" : foreground, "bg": background},
        TabLineFill={"style": "NONE"},
        VertSplit={"fg": background},
        vCursor={"fg": "NONE", "bg": "NONE", "style": 'reverse'},
        WarningMsg={"fg": yellow, "bg": "NONE", "style": 'bold'},
        Whitespace={"fg": bg_bright},
        WildMenu={"fg": foreground, "bg": green},
        Visual={"fg": "NONE", "bg": bg_bright},
        VisualNOS={"fg": background, "bg": foreground},
    )
    nvim_plugins = base.NeovimPluginTheme()

