from thematic.themes import base


class Theme(base.Theme):
    foreground = "#C0C0C0"
    background = "#101010"
    bg_bright = "#181818"
    bg_brighter = "#252525"
    bg_brightest = "#282828"

    peach = "#EFA6A2"
    green ="#80C990"
    yellow = "#A69460"
    blue = "#A3B8EF"
    pink = "#E6A3DC"
    cyan = "#50CACD"
    white = "#808080"
    black = "#454545"
    orange = "#E0AF85"
    green_bright = "#5ACCAF"
    yellow_bright = "#C8C874"
    purple = "#CCACED"
    pink_bright = "#F2A1C2"
    cyan_bright = "#74C3E4"
    white_bright = "#C0C0C0"

    autosuggestions = "238"
    tmux_mode_fg = cyan

    xcolors = base.Xcolors(
        foreground=foreground,
        background=background,
        xcolors_00=black,
        xcolors_01=peach,
        xcolors_02=green,
        xcolors_03=yellow,
        xcolors_04=blue,
        xcolors_05=purple,
        xcolors_06=cyan,
        xcolors_07=white,
        xcolors_08=black,
        xcolors_09=orange,
        xcolors_10=green_bright,
        xcolors_11=yellow_bright,
        xcolors_12=blue,
        xcolors_13=purple,
        xcolors_14=cyan_bright,
        xcolors_15=white_bright,
    )

    nvim_core = base.NeovimTheme(
        Boolean={"fg": green},
        BufferCurrent={"fg": yellow, "bg": background, "style": "bold"},
        BufferCurrentMod={"fg": blue, "bg": background},
        BufferCurrentSign={"fg": blue, "bg": background},
        BufferInactive={"fg": foreground, "bg": bg_bright},
        BufferInactiveMod={"fg": blue, "bg": bg_bright},
        BufferInactiveSign={"fg": blue, "bg": bg_bright},
        BufferInactiveTarge={"fg": foreground, "bg": bg_bright},
        BufferTabPageFill={"fg": blue, "bg": background},
        Character={"fg": green},
        ColorColumn={"fg": "NONE", "bg": bg_bright},
        Comment={"fg": black, "style": "italic"},
        Conceal={"fg": bg_bright, "bg": "NONE"},
        Conditional={"fg": purple},
        Constant={"fg": yellow, "style": "italic"},
        Cursor={"fg": "NONE", "bg": "NONE", "style": "reverse"},
        CursorColumn={"fg": "NONE", "bg": black},
        CursorIM={"fg": "NONE", "bg": "NONE", "style": "reverse"},
        CursorLine={"fg": "NONE", "bg": bg_bright},
        CursorLineNr={"fg": blue, "bg": bg_bright, "style": "bold"},
        Define={"fg": purple},
        DiffAdd={"fg": background, "bg": green},
        DiffChange={"fg": background, "bg": yellow},
        DiffDelete={"fg": background, "bg": pink},
        DiffText={"fg": background, "bg": foreground},
        Directory={"fg": bg_bright, "bg": "NONE"},
        EndOfBuffer={"fg": background, "bg": "NONE"},
        Error={"fg": pink},
        ErrorMsg={"fg": pink, "bg": "NONE", "style": "bold"},
        Exception={"fg": purple},
        Float={"fg": green},
        FoldColumn={"fg": foreground, "bg": background},
        Folded={"fg": bg_bright, "bg": bg_bright},
        Function={"fg": blue},
        Identifier={"fg": cyan},
        IncSearch={"fg": bg_bright, "bg": yellow, "style": "NONE"},
        Include={"fg": purple},
        Keyword={"fg": purple},
        Label={"fg": yellow},
        LineNr={"fg": black},
        Macro={"fg": yellow},
        MatchParen={"fg": pink, "bg": "NONE"},
        ModeMsg={"fg": foreground, "bg": "NONE", "style": "bold"},
        NonText={"fg": bg_bright},
        NormalFloat={"fg": foreground, "bg": bg_bright},
        Number={"fg": green},
        Operator={"fg": purple},
        Pmenu={"fg": foreground, "bg": bg_bright},
        PmenuSbar={"fg": "NONE", "bg": bg_bright},
        PmenuSel={"fg": bg_bright, "bg": blue},
        PmenuSelBold={"fg": bg_bright, "g": blue},
        PmenuThumb={"fg": purple, "bg": green},
        PreCondit={"fg": purple},
        PreProc={"fg": purple},
        Question={"fg": yellow},
        QuickFixLine={"fg": purple, "style": "bold"},
        Repeat={"fg": purple},
        Search={"fg": background, "bg": yellow},
        Special={"fg": blue},
        SpecialChar={"fg": yellow},
        SpecialComment={"fg": bg_bright},
        SpecialKey={"fg": bg_bright},
        SpellBad={"fg": pink, "bg": "NONE", "style": "undercurl"},
        SpellCap={"fg": "bue", "bg": "NONE", "style": "undercurl"},
        SpellLocal={"fg": cyan, "bg": "NONE", "style": "undercurl"},
        SpellRare={"fg": purple, "bg": "NONE", "style": "undercurl"},
        Statement={"fg": purple},
        StatusLine={"fg": bg_bright, "bg": bg_brighter, "style": "NONE"},
        StatusLineNC={"fg": bg_bright, "bg": bg_bright, "style": "NONE"},
        StorageClass={"fg": pink, "style": "italic"},
        String={"fg": green},
        Structure={"fg": pink, "style": "italic"},
        TSAnnotation={"fg": purple},
        TSAttribute={"fg": yellow},
        TSBoolean={"fg": green},
        TSCharacter={"fg": green},
        TSConstBuiltin={"fg": cyan, "style": "italic"},
        TSConstant={"fg": pink, "style": "italic"},
        TSConstructor={"fg": foreground},
        TSFunction={"fg": blue},
        TSFunctionBuiltin={"fg": blue},
        TSInclude={"fg": purple},
        TSKeywordFunction={"fg": purple},
        TSKeywordOperator={"fg": purple},
        TSLabel={"fg": purple},
        TSMath={"fg": green},
        TSMethod={"fg": blue},
        TSNamespace={"fg": yellow},
        TSNumber={"fg": yellow},
        TSParameter={"fg": pink, "style": "italic"},
        TSPunctDelimitter={"fg": bg_brighter},
        TSPunctSpecial={"fg": yellow},
        TSSymbol={"fg": yellow},
        TSText={"fg": green},
        TSType={"fg": yellow},
        TSTypeBuiltin={"fg": yellow},
        TSVariable={"fg": pink},
        TSVariableBuiltin={"fg": cyan},
        TabLineFill={"style": "NONE"},
        TabLineSel={"bg": background},
        Tag={"fg": yellow},
        Terminal={"fg": foreground, "bg": background},
        Title={"fg": purple, "style": "bold"},
        Todo={"fg": yellow, "style": "italic"},
        Type={"fg": pink, "style": "italic"},
        Typedef={"fg": purple},
        Underlined={"style": "underline"},
        VertSplit={"fg": background},
        Visual={"fg": "NONE", "bg": bg_brighter},
        VisualNOS={"fg": background, "bg": foreground, "style": "underline"},
        WarningMsg={"fg": yellow, "bg": "NONE", "style": "bold"},
        Whitespace={"fg": bg_bright},
        WildMenu={"fg": foreground, "bg": green},
        debugBreakpoint={"fg": background, "bg": pink},
        iCursor={"fg": bg_bright, "bg": "NONE", "style": "reverse"},
        lCursor={"fg": "NONE", "bg": "NONE", "style": "reverse"},
        vCursor={"fg": "NONE", "bg": "NONE", "style": "reverse"},
    )
    nvim_plugins = base.NeovimPluginTheme(
        NvimTreeFolderName={"fg": foreground},
        NvimTreeEmptyFolderName={"fg": bg_brighter},
        NvimTreeOpenedFolderName={"fg": foreground},
    )
