from thematic.themes import base


class Theme(base.Theme):
    background = "#191724"
    surface = "#1f1d2e"
    overlay = "#26233a"
    inactive = "#555169"
    subtle = "#6e6a86"
    text = "#e0def4"
    love = "#eb6f92"
    gold = "#f6c177"
    rose = "#ebbcba"
    pine = "#31748f"
    foam = "#9ccfd8"
    iris = "#c4a7e7"
    highlight = "#2a2837"
    highlight_inactive = "#211f2d"
    highlight_overlay = "#3a384a"
    ########
    foreground = text
    bg_bright = overlay
    bg_brighter = highlight_overlay
    bg_brightest = subtle

    black = highlight_inactive
    red = love
    green = gold
    yellow = foam
    blue = pine
    purple = iris
    cyan = rose
    cyan_bright = rose
    white = subtle
    black_bright = highlight_overlay
    red_bright = love
    green_bright = pine
    yellow_bright = foam
    blue_bright = subtle
    purple_bright = iris
    white_bright = text
    cursor = inactive
    cursor_text = text

    autosuggestions = "238"
    tmux_mode_fg = blue

    xcolors = base.Xcolors(
        foreground=foreground,
        background=background,
        xcolors_00=black,
        xcolors_01=red,
        xcolors_02=green,
        xcolors_03=yellow,
        xcolors_04=blue,
        xcolors_05=purple,
        xcolors_06=cyan,
        xcolors_07=white,
        xcolors_08=black_bright,
        xcolors_09=red_bright,
        xcolors_10=green_bright,
        xcolors_11=yellow_bright,
        xcolors_12=blue_bright,
        xcolors_13=purple_bright,
        xcolors_14=cyan_bright,
        xcolors_15=white_bright,
    )
    nvim_core = base.NeovimTheme(
        Boolean={"fg": green},
        BufferCurrent={"fg": yellow, "bg": background, "style": "bold"},
        BufferCurrentMod={"fg": blue, "bg": background},
        BufferCurrentSign={"fg": blue, "bg": background},
        BufferInactive={"fg": foreground, "bg": bg_bright},
        BufferInactiveMod={"fg": blue, "bg": bg_bright},
        BufferInactiveSign={"fg": blue, "bg": bg_bright},
        BufferInactiveTarge={"fg": foreground, "bg": bg_bright},
        BufferTabPageFill={"fg": blue, "bg": background},
        Character={"fg": green},
        ColorColumn={"fg": "NONE", "bg": bg_bright},
        Comment={"fg": highlight_overlay, "style": "italic"},
        Conceal={"fg": bg_bright, "bg": "NONE"},
        Conditional={"fg": purple},
        Constant={"fg": yellow, "style": "italic"},
        Cursor={"fg": "NONE", "bg": "NONE", "style": "reverse"},
        CursorColumn={"fg": "NONE", "bg": black_bright},
        CursorIM={"fg": "NONE", "bg": "NONE", "style": "reverse"},
        CursorLine={"fg": "NONE", "bg": bg_bright},
        CursorLineNr={"fg": blue, "bg": bg_bright, "style": "bold"},
        Define={"fg": purple},
        DiffAdd={"fg": background, "bg": green},
        DiffChange={"fg": background, "bg": yellow},
        DiffDelete={"fg": background, "bg": red},
        DiffText={"fg": background, "bg": foreground},
        Directory={"fg": bg_bright, "bg": "NONE"},
        EndOfBuffer={"fg": background, "bg": "NONE"},
        Error={"fg": red},
        ErrorMsg={"fg": red, "bg": "NONE", "style": "bold"},
        Exception={"fg": purple},
        Float={"fg": green},
        FoldColumn={"fg": foreground, "bg": background},
        Folded={"fg": bg_bright, "bg": bg_bright},
        Function={"fg": blue},
        Identifier={"fg": cyan},
        IncSearch={"fg": bg_bright, "bg": yellow, "style": "NONE"},
        Include={"fg": purple},
        Keyword={"fg": purple},
        Label={"fg": yellow},
        LineNr={"fg": black_bright},
        Macro={"fg": yellow},
        MatchParen={"fg": red, "bg": "NONE"},
        ModeMsg={"fg": foreground, "bg": "NONE", "style": "bold"},
        NonText={"fg": bg_bright},
        NormalFloat={"fg": foreground, "bg": bg_bright},
        Number={"fg": green},
        Operator={"fg": purple},
        Pmenu={"fg": foreground, "bg": bg_bright},
        PmenuSbar={"fg": "NONE", "bg": bg_bright},
        PmenuSel={"fg": bg_bright, "bg": blue},
        PmenuSelBold={"fg": bg_bright, "g": blue},
        PmenuThumb={"fg": purple, "bg": green},
        PreCondit={"fg": purple},
        PreProc={"fg": purple},
        Question={"fg": yellow},
        QuickFixLine={"fg": purple, "style": "bold"},
        Repeat={"fg": purple},
        Search={"fg": background, "bg": yellow},
        Special={"fg": blue},
        SpecialChar={"fg": yellow},
        SpecialComment={"fg": bg_bright},
        SpecialKey={"fg": bg_bright},
        SpellBad={"fg": red, "bg": "NONE", "style": "undercurl"},
        SpellCap={"fg": "bue", "bg": "NONE", "style": "undercurl"},
        SpellLocal={"fg": cyan, "bg": "NONE", "style": "undercurl"},
        SpellRare={"fg": purple, "bg": "NONE", "style": "undercurl"},
        Statement={"fg": purple},
        StatusLine={"fg": bg_bright, "bg": bg_brighter, "style": "NONE"},
        StatusLineNC={"fg": bg_bright, "bg": bg_bright, "style": "NONE"},
        StorageClass={"fg": red, "style": "italic"},
        String={"fg": green},
        Structure={"fg": red, "style": "italic"},
        TSAnnotation={"fg": purple},
        TSAttribute={"fg": yellow},
        TSBoolean={"fg": green},
        TSCharacter={"fg": green},
        TSConstBuiltin={"fg": cyan, "style": "italic"},
        TSConstant={"fg": red, "style": "italic"},
        TSConstructor={"fg": foreground},
        TSFunction={"fg": blue},
        TSFunctionBuiltin={"fg": blue},
        TSInclude={"fg": purple},
        TSKeywordFunction={"fg": purple},
        TSKeywordOperator={"fg": purple},
        TSLabel={"fg": purple},
        TSMath={"fg": green},
        TSMethod={"fg": blue},
        TSNamespace={"fg": yellow},
        TSNumber={"fg": yellow},
        TSParameter={"fg": red, "style": "italic"},
        TSPunctDelimitter={"fg": bg_brighter},
        TSPunctSpecial={"fg": yellow},
        TSSymbol={"fg": yellow},
        TSText={"fg": green},
        TSType={"fg": yellow},
        TSTypeBuiltin={"fg": yellow},
        TSVariable={"fg": red},
        TSVariableBuiltin={"fg": cyan},
        TabLineFill={"style": "NONE"},
        TabLineSel={"bg": background},
        Tag={"fg": yellow},
        Terminal={"fg": foreground, "bg": background},
        Title={"fg": purple, "style": "bold"},
        Todo={"fg": yellow, "style": "italic"},
        Type={"fg": red, "style": "italic"},
        Typedef={"fg": purple},
        Underlined={"style": "underline"},
        VertSplit={"fg": background},
        Visual={"fg": "NONE", "bg": bg_brighter},
        VisualNOS={"fg": background, "bg": foreground, "style": "underline"},
        WarningMsg={"fg": yellow, "bg": "NONE", "style": "bold"},
        Whitespace={"fg": bg_bright},
        WildMenu={"fg": foreground, "bg": green},
        debugBreakpoint={"fg": background, "bg": red},
        iCursor={"fg": bg_bright, "bg": "NONE", "style": "reverse"},
        lCursor={"fg": "NONE", "bg": "NONE", "style": "reverse"},
        vCursor={"fg": "NONE", "bg": "NONE", "style": "reverse"},
    )
    nvim_plugins = base.NeovimPluginTheme(
        NvimTreeFolderName={"fg": foreground},
        NvimTreeEmptyFolderName={"fg": bg_brighter},
        NvimTreeOpenedFolderName={"fg": foreground},
        CocUnusedHighlight={"fg": bg_brighter},
    )
