from thematic.themes import base


class TokyoNight(base.Theme):
    name = "tokyo-night"
    bg_dark = "#1f2335"
    background = "#24283b"
    bg_bright = "#292e42"
    bg_brighter = "#3b4261"
    bg_brightest = "#545c7e"

    black = "#414868"
    foreground = "#c0caf5"
    fg_dark = "#a9b1d6"
    comment = "#565f89"
    dark5 = "#737aa2"
    blue0 = "#3d59a1"
    blue = "#7aa2f7"
    cyan = "#7dcfff"
    blue1 = "#2ac3de"
    blue2 = "#0db9d7"
    blue5 = "#89ddff"
    blue6 = "#B4F9F8"
    blue7 = "#394b70"
    purple_bright = "#bb9af7"
    purple = "#9d7cd8"
    orange = "#ff9e64"
    yellow = "#e0af68"
    green = "#9ece6a"
    green1 = "#73daca"
    green2 = "#41a6b5"
    teal = "#1abc9c"
    red = "#f7768e"
    red1 = "#db4b4b"

    autosuggestions = "238"
    tmux_mode_fg = blue2

    xcolors = base.Xcolors(
        foreground=foreground,
        background=background,
        xcolors_00=black,
        xcolors_01=red,
        xcolors_02=green,
        xcolors_03=yellow,
        xcolors_04=blue,
        xcolors_05=purple,
        xcolors_06=cyan,
        xcolors_07=dark5,
        xcolors_08=bg_brighter,
        xcolors_09=red1,
        xcolors_10=green1,
        xcolors_11=orange,
        xcolors_12=blue1,
        xcolors_13=purple_bright,
        xcolors_14=teal,
        xcolors_15=comment,
    )
    nvim_core = base.NeovimTheme(
        Boolean={"fg": green},
        BufferCurrent={"fg": yellow, "bg": background, "style": "bold"},
        BufferCurrentMod={"fg": blue, "bg": background},
        BufferCurrentSign={"fg": blue, "bg": background},
        BufferInactive={"fg": foreground, "bg": bg_brighter},
        BufferInactiveMod={"fg": blue, "bg": bg_brighter},
        BufferInactiveSign={"fg": blue, "bg": bg_brighter},
        BufferInactiveTarge={"fg": foreground, "bg": bg_brighter},
        BufferTabPageFill={"fg": blue, "bg": background},
        Character={"fg": green},
        ColorColumn={"fg": "NONE", "bg": bg_brighter},
        Comment={"fg": comment, "style": "italic"},
        Conceal={"fg": bg_brighter, "bg": "NONE"},
        Conditional={"fg": purple},
        Constant={"fg": yellow, "style": "italic"},
        Cursor={"fg": "NONE", "bg": "NONE", "style": "reverse"},
        CursorColumn={"fg": "NONE", "bg": comment},
        CursorIM={"fg": "NONE", "bg": "NONE", "style": "reverse"},
        CursorLine={"fg": "NONE", "bg": bg_brighter},
        CursorLineNr={"fg": blue, "bg": bg_brighter, "style": "bold"},
        Define={"fg": purple},
        DiffAdd={"fg": background, "bg": green},
        DiffChange={"fg": background, "bg": yellow},
        DiffDelete={"fg": background, "bg": red},
        DiffText={"fg": background, "bg": foreground},
        Directory={"fg": bg_brighter, "bg": "NONE"},
        EndOfBuffer={"fg": background, "bg": "NONE"},
        Error={"fg": red},
        ErrorMsg={"fg": red, "bg": "NONE", "style": "bold"},
        Exception={"fg": purple},
        Float={"fg": green},
        FoldColumn={"fg": foreground, "bg": background},
        Folded={"fg": bg_brighter, "bg": bg_brighter},
        Function={"fg": blue},
        Identifier={"fg": cyan},
        IncSearch={"fg": bg_brighter, "bg": yellow, "style": "NONE"},
        Include={"fg": purple},
        Keyword={"fg": purple},
        Label={"fg": yellow},
        LineNr={"fg": comment},
        Macro={"fg": yellow},
        MatchParen={"fg": red, "bg": "NONE"},
        ModeMsg={"fg": foreground, "bg": "NONE", "style": "bold"},
        NonText={"fg": bg_brighter},
        NormalFloat={"fg": foreground, "bg": bg_brighter},
        Number={"fg": green},
        Operator={"fg": purple},
        Pmenu={"fg": foreground, "bg": bg_brighter},
        PmenuSbar={"fg": "NONE", "bg": bg_brighter},
        PmenuSel={"fg": bg_brighter, "bg": blue},
        PmenuSelBold={"fg": bg_brighter, "g": blue},
        PmenuThumb={"fg": purple, "bg": green},
        PreCondit={"fg": purple},
        PreProc={"fg": purple},
        Question={"fg": yellow},
        QuickFixLine={"fg": purple, "style": "bold"},
        Repeat={"fg": purple},
        Search={"fg": background, "bg": yellow},
        Special={"fg": blue},
        SpecialChar={"fg": yellow},
        SpecialComment={"fg": bg_brighter},
        SpecialKey={"fg": bg_brighter},
        SpellBad={"fg": red, "bg": "NONE", "style": "undercurl"},
        SpellCap={"fg": "bue", "bg": "NONE", "style": "undercurl"},
        SpellLocal={"fg": cyan, "bg": "NONE", "style": "undercurl"},
        SpellRare={"fg": purple, "bg": "NONE", "style": "undercurl"},
        Statement={"fg": purple},
        StatusLine={"fg": bg_brighter, "bg": dark5, "style": "NONE"},
        StatusLineNC={"fg": bg_brighter, "bg": bg_brighter, "style": "NONE"},
        StorageClass={"fg": red, "style": "italic"},
        String={"fg": green},
        Structure={"fg": red, "style": "italic"},
        TSAnnotation={"fg": purple},
        TSAttribute={"fg": yellow},
        TSBoolean={"fg": green},
        TSCharacter={"fg": green},
        TSConstBuiltin={"fg": cyan, "style": "italic"},
        TSConstant={"fg": red, "style": "italic"},
        TSConstructor={"fg": foreground},
        TSFunction={"fg": blue},
        TSFunctionBuiltin={"fg": blue},
        TSInclude={"fg": purple},
        TSKeywordFunction={"fg": purple},
        TSKeywordOperator={"fg": purple},
        TSLabel={"fg": purple},
        TSMath={"fg": green},
        TSMethod={"fg": blue},
        TSNamespace={"fg": yellow},
        TSNumber={"fg": yellow},
        TSParameter={"fg": red, "style": "italic"},
        TSPunctDelimitter={"fg": dark5},
        TSPunctSpecial={"fg": yellow},
        TSSymbol={"fg": yellow},
        TSText={"fg": green},
        TSType={"fg": yellow},
        TSTypeBuiltin={"fg": yellow},
        TSVariable={"fg": red},
        TSVariableBuiltin={"fg": cyan},
        TabLineFill={"style": "NONE"},
        TabLineSel={"bg": background},
        Tag={"fg": yellow},
        Terminal={"fg": foreground, "bg": background},
        Title={"fg": purple, "style": "bold"},
        Todo={"fg": yellow, "style": "italic"},
        Type={"fg": red, "style": "italic"},
        Typedef={"fg": purple},
        Underlined={"style": "underline"},
        VertSplit={"fg": background},
        Visual={"fg": "NONE", "bg": black},
        VisualNOS={"fg": background, "bg": foreground, "style": "underline"},
        WarningMsg={"fg": yellow, "bg": "NONE", "style": "bold"},
        Whitespace={"fg": bg_brighter},
        WildMenu={"fg": foreground, "bg": green},
        debugBreakpoint={"fg": background, "bg": red},
        iCursor={"fg": bg_brighter, "bg": "NONE", "style": "reverse"},
        lCursor={"fg": "NONE", "bg": "NONE", "style": "reverse"},
        vCursor={"fg": "NONE", "bg": "NONE", "style": "reverse"},
    )
    nvim_plugins = base.NeovimPluginTheme()
